apiVersion: v1
kind: ConfigMap
metadata:
  name: le-nextgen
  namespace: {{ .Release.Namespace }}
data:
  https_port: "10800"
  learning_env: "on_prem"
  server_url: "http://cv-nextgen:6060"
  service_secret: 59MR5RlVARcdH7zb7pNx6GzqiglBmXR8
